### PR TITLE
small improvements

### PR DESCRIPTION
**Pull request by fogti**
Similiar to https://github.com/irrustible/async-oneshot/pull/7, this PR tries to fix a few things I noticed...

### CODE REVIEW

**Comment by jjl** [comment]
Aside from the reformatting, fine. Though it's possible you'll hack on this more than i will. Shan't link it, but there's an issue about this library open on futures-lite for a while and someone is asking awkward questions and my enthusiasm to figure out what should and shouldn't be here is limited right now.

**Comment by jjl** [comment]
oh, incidentally, stjepang noted that async fn wrapping can also increase memory usage. though i gather he measured this a while ago and it might be handled better by the compiler now.

**Comment by fogti** [comment]
My experience was primarily that it increases cpu usage (in performance critical inner loop bodies) and increases executable size... but increased ram memory usage is certainly possible...

I first tried to just reformat a few things I noticed, but I didn't think that the reformatting is that bad... This code didn't seem to have edges where whitespace-aligned code or such exists or helps readability... But regardless of that, I intentionally did the reformatting in the last commit, such that this PR could be easily applied partially.

**Comment by fogti** [comment]
Ah ok, I found that thread... It would be interesting to replace `poll_state` with a slim wrapper around `poll_fn`, tho...

**Comment by jjl** [comment]
would you like to look into that? i can take it with or without.

**Comment by fogti** [comment]
I'll look into it, but it would take some time (maybe I can get it to work tomorrow, maybe not)... If I'm not able to finish it until `Oct 12, 2020`, you can merge this as-is.

**Comment by fogti** [comment]
It is outside of the scope of this PR, but I think we should get rid of the trivial wrappers `Ready` and `Pending` (both can be trivially replaced using `poll_fn`)...

```rust
pending() => poll_fn(|_| Poll::Pending)

// either:
fn ready<T>(x: T) -> impl Future<Output = T> {
    let mut x = Some(x);
    poll_fn(move |_| Poll::Ready(x.take().expect("called after completion")))
}
// or:
fn ready<T>(x: T) -> impl Future<Output = T> {
    async { x }
}
```

or we should deprecate `poll_state`, `pending` and `ready`...

**Comment by jjl** [comment]
Thanks!

**Pull request merged**
