### PR TITLE
Release v0.4.0

### LINKED ISSUE #5: license info mismatch between `README.md` and `Cargo.toml`
In `README.md`, it is stated that `futures-micro` is licensed under `MIT OR Apache-2.0`, but in `Cargo.toml`, license is set to `MPL-2.0`. This should be fixed.

### LINKED ISSUE #6: [planning] Remove deprecated functions
Currently, the futures-micro:main branch is in a somewhat undesired state. The code declares some functions as deprecated, but the code itself is also somewhat incompatible to `v0.3.*`, which means it would need 2 minor version bumps (1 to declare the functions as deprecated, 1 to finally remove them).
I'm unsure if it would be possible to speed this up. I would like these superfluous functions to be removed basically "right now", so that we can release an `v0.4.0` without them. But to guarantee that this goes smoothly, we would basically need to patch all dependent crates which use these functions and remove those usages before releasing the `v0.4` version. The migration recommendations in `README.md` should be left there until version `0.5`.

Dependent crates (search queries: [github.com](https://github.com/search?p=3&q=futures-micro&type=Code), [crates.io](https://crates.io/crates/futures-micro/reverse_dependencies)):
* [X] [`async-oneshot`](https://github.com/irrustible/async-oneshot), patched in [#12](https://github.com/irrustible/async-oneshot/pull/12)
* [ ] [`async-oneshot-local`](https://github.com/irrustible/async-oneshot-local), "but" currently broken regardless of that.
* [X] https://github.com/r3v2d0g/ufut, nothing to patch (just reexports anything via wildcard)
* [ ] [`async-spsc`](https://github.com/irrustible/async-spsc), needs to be patched, [#1](https://github.com/irrustible/async-spsc/pull/1)
* [X] https://github.com/jacobrosenthal/sophon_tweets, nothing to patch (only uses `or!`)
* [X] https://github.com/YZITE/encsess2, nothing to patch (only uses `poll_fn`)
* [X] https://github.com/YZITE/yxd-auth, nothing to patch (only uses `poll_fn`)

### PR DESCRIPTION
**Pull request by fogti**
~~blocked on agreement on #5.~~

Fixes #5. Fixes #6.

This PR changes the license of `futures-micro` to `Apache-2.0 WITH LLVM-exception` and thus needs approval from all previous contributors.

* [x] @jjl
* [X] @zserik 
* [x] @r3v2d0g 
* [x] @stjepang (probably not really needed, but it's good to be on the safe side)

P.S. sorry for the spam, but I want to ensure that a consensus is found and approved to move forward.

### CODE REVIEW

**Comment by jjl** [comment]
Couple of things:

- still has copyrights for other libs that we no longer have any code from
- the top of the license file refers to us as the llvm project

**Comment by fogti** [comment]
@jjl what concrete stuff do you mean with "still has copyrights for other libs that we no longer have any code from"?

**Comment by jjl** [comment]
~ line 70 of the readme:

```
Copyright (c) 2017 The Tokio Authors
Copyright (c) 2016 Alex Crichton
```

**Comment by zserik** [comment]
I'm going to squash the commits. This can then be merged.

**Comment by fogti** [comment]
@jjl This is ready to be merged. The license is changed to `Apache-2.0 WITH LLVM-exception` in `453bea4` as stated above. All previous contributors accepted the change.

**Comment by jjl** [comment]
Released and tagged v0.4.0

**Pull request merged**
